#application
server:
  port: 50500
  tomcat.max-threads: 20

#monitoring
management:
    endpoint:
      health:
        show-details: always
    endpoints:
      web:
        exposure:
          include: "health,prometheus,heapdump"

springdoc.swagger-ui.path: /swagger-ui/index.html

#jaeger / zipkin
spring.zipkin.service.name: "callee-service"
spring.zipkin.enabled: true
spring.sleuth.enabled: ${spring.zipkin.enabled}
logging.level.zipkin2: "FATAL"

#security
security.authentication.enabled: false

spring.security.user.name: "admin"
spring.security.user.password: "admin"

#persistence
spring.datasource.url: jdbc:h2:mem:filestorage
#spring.datasource.url: jdbc:postgresql://localhost:5432/postgres
spring.datasource.username: postgres
spring.datasource.password: postgres

spring.datasource.hikari.maximum-pool-size: "10"
spring.datasource.hikari.connection-timeout: "10000"

spring.sql.init.mode: always
spring.sql.init.schema-locations: classpath*:db/migration/V1__init.sql
spring.jpa.hibernate.ddl-auto: none

database.provisioning.goals: -import-demo-data

#logging
logging.level.root: "WARN"
logging.level.org.springframework: "INFO"

logging.level.org.goafabric: "INFO"
logging.level.org.flywaydb.core: "INFO"
logging.level.org.hibernate.SQL: "DEBUG"

#Profile can be either s3 or sql
spring.profiles.active: "sql-object-storage"

#Amazon S3 configuration, optional with profile sql
cloud.aws.s3.bucket.name: "objects"

cloud.aws.s3.endpoint: "http://localhost:9100"
cloud.aws.s3.path-style.enabled: "true"
cloud.aws.credentials.access-key: "minioadmin"
cloud.aws.credentials.secret-key: "minioadmin"



