version: '3.7'
services:
  postgres:
    container_name: ${_Values_root_name}-postgres
    image: postgres:15.1
    restart: 'no'
    ports:
      - 5432:5432
    command: postgres -c 'shared_buffers=128MB' -c 'max_connections=30' -c 'shared_preload_libraries=pg_stat_statements'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ${_Values_root_name}-net
    environment:
      TZ: "Europe/Berlin"
      POSTGRES_DB: "objectstorage"

      #secrets
      POSTGRES_USER: "object-storage-service"
      POSTGRES_PASSWORD: "object-storage-service"
  s3:
    container_name: ${_Values_root_name}-s3
    command: server /data --console-address ':9001'
    image: quay.io/minio/minio:RELEASE.2023-01-25T00-19-54Z
    restart: 'no'
    ports:
      - 9100:9000
      - 9101:9001
    volumes:
      - miniodata:/data
    networks:
      - ${_Values_root_name}-net
    environment:
      TZ: "Europe/Berlin"


volumes:
  pgdata:
    driver: local
  miniodata:
    driver: local


networks:
  object-storage-database-net:
    driver: bridge
