version: "3.7"

services:
  object-storage-service:
    container_name: ${_Values_root_name}-application
    image:  ${_Values_image_repository}${_Values_image_native}:${_Values_image_tag}
    restart: 'no'
    ports:
      - "${_Values_service_port}:${_Values_service_port}"
    command: ["-Xmx${_Values_resources_requests_memory}"]

    healthcheck:
      test: "curl -f http://localhost:${_Values_service_port}/actuator/health || exit 1"
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - tmp:/tmp
      - applogs:/usr/share/logs
    networks:
      - ${_Values_root_name}-net
    environment:
      #application
      TZ: Europe/Berlin
      server.port: "${_Values_service_port}"
      server.tomcat.threads.max: "20"
      server.forward-headers-strategy: FRAMEWORK

      #security
      security.authentication.enabled: "false"

      #monitoring
      management.endpoint.health.show-details: always
      management.endpoints.web.exposure.include: "health,heapdump,circuitbreakers,prometheus"

      #profile
      spring.profiles.active: "s3-object-storage"

      #persistence
      spring.datasource.url: "jdbc:postgresql://host.docker.internal:5432/objectstorage"

      #s3
      cloud.aws.s3.bucket.name: "objects"
      cloud.aws.s3.endpoint: "http://host.docker.internal:9100"
      cloud.aws.s3.path-style.enabled: "true"

      #secrets
      spring.datasource.username: "object-storage-service"
      spring.datasource.password: "object-storage-service"

      cloud.aws.credentials.access-key: "minioadmin"
      cloud.aws.credentials.secret-key: "minioadmin"

      #log levels
      logging.level.root: "WARN"
      logging.level.org.goafabric: "INFO"
      logging.level.org.springframework: "INFO"

volumes:
    tmp:
    applogs:

networks:
  object-storage-service-net:
    driver: bridge